### PR TITLE
Package context size

### LINKED ISSUE #223: Persistent model configuration (`max_tokens`, `temperature`, etc.)
DMR has no way to change or persist model runtime parameters like `temperature` or `max_tokens`. 
(At least I couldn't find it, I might be wrong)

The default context window (4096 tokens) is far too small for multi-turn or reasoning-heavy workloads. 

> i.e.: running agents through Microsoft Agent Framework or Docker cagent, every time Docker Desktop restarts, the model reloads with that limit, and long conversations just crash mid-session. (cagen, indeed, crash silently)

I’ve written a full analysis here -> [How to change context size for Docker Model Runner (DMR)](https://jgcarmona.com/change-dmr-context-size/)

And a working PowerShell script that forces DMR to reload a model with a new context window -> [set-model-context-size.ps1](https://github.com/juangcarmona/ms-agent-framework-playground/blob/main/labs/dotnet/set-model-context-size.ps1)

> That "hack" works by launching a temporary agent with a higher `max_tokens` flag... but it’s clearly not the right way to do it. nevertheless, if cagent can do it, the API, should be able to do it... Which, again, tells me there must be an undocumented way... 

So, here is my

## Proposal

Add a proper CLI or API for persistent model configuration, for example:

```
docker model set ai/gpt-oss --context-size 32768 --temperature 0.7
```

This would store and apply parameters for that model instance across restarts, instead of forcing users to reload or “hack” them through cagent. Persistent configuration would make DMR much more practical for multi-agent and RAG workloads, where context window and temperature really matter.

### PR DESCRIPTION
**Pull request by ilopezluna**
fixes #223

How to use it:
```
docker model ls | grep smollm2
ai/smollm2                      361.82 M    IQ2_XXS/Q4_K_M  llama         354bf30d0aa3  6 months ago  256.35 MiB  

docker model inspect ai/smollm2
{
    "id": "sha256:354bf30d0aa3af413d2aa5ae4f23c66d78980072d1e07a5b0d776e9606a2f0b9",
    "tags": [
        "ai/smollm2"
    ],
    "created": 1742816981,
    "config": {
        "format": "gguf",
        "quantization": "IQ2_XXS/Q4_K_M",
        "parameters": "361.82 M",
        "architecture": "llama",
        "size": "256.35 MiB"
    }
}


docker model package --from ai/smollm2 --context-size 2048 ignaciolopezluna020/smollm2:2k
INFO[0000] Successfully initialized store               
Reading model from store: "ai/smollm2"
INFO[0000] Getting model by reference: ai/smollm2       
Creating builder from existing model
Setting context size 2048
Creating lightweight model variant...
INFO[0000] Writing lightweight model variant            
Model variant created successfully


docker model ls | grep smollm2
ai/smollm2                      361.82 M    IQ2_XXS/Q4_K_M  llama         354bf30d0aa3  6 months ago  256.35 MiB  
ignaciolopezluna020/smollm2:2k  361.82 M    IQ2_XXS/Q4_K_M  llama         7522a58ecdbd  6 months ago  256.35 MiB  


docker model inspect ignaciolopezluna020/smollm2:2k
{
    "id": "sha256:7522a58ecdbda6cdeea5480bebd456329e65fc4bec7cd9484193a2813d4b3413",
    "tags": [
        "ignaciolopezluna020/smollm2:2k"
    ],
    "created": 1742816981,
    "config": {
        "format": "gguf",
        "quantization": "IQ2_XXS/Q4_K_M",
        "parameters": "361.82 M",
        "architecture": "llama",
        "size": "256.35 MiB",
        "context_size": 2048
    }
}
```

This pull request adds support for creating new model variants by repackaging an existing model, allowing users to make config-only modifications (such as changing context size) without re-uploading or duplicating large model files. It introduces a new `--from` flag to the `docker model package` command, implements lightweight repackaging logic, and ensures that only config changes (with no new files) use this optimized path. The changes also include new tests for the repackaging workflow.

**New packaging source and CLI enhancements:**

- Added a `--from <model>` flag to the `docker model package` command, allowing users to repackage an existing model as a new variant. The CLI now validates that only one of `--gguf`, `--safetensors-dir`, or `--from` is provided. 

**Builder and distribution logic:**

- Introduced the `FromModel` function in the `builder` package to create a new builder from an existing model artifact, enabling modifications such as changing config or adding layers. Also added a `Model()` method to access the underlying model artifact.
- Added logic in the CLI to detect config-only modifications and, when appropriate, use a new lightweight repackaging path that avoids copying model layers.

**Lightweight repackaging implementation:**

- Implemented `WriteLightweightModel` in the distribution client and `WriteLightweight` in the local store, enabling efficient creation of new model variants by writing only the manifest and config when all layers already exist in the store.

**Testing and validation:**

- Added comprehensive tests to verify the repackaging workflow, ensuring that config changes and additional layers are handled correctly and that the lightweight repackaging path preserves layers and media types.

**Dependency and import updates:**

- Imported the `distribution` package in the CLI to support the new distribution client functionality.

## Summary by Sourcery

Introduce lightweight repackaging of existing Docker model artifacts to enable config-only variants without duplicating layer data. Add a new --from flag to docker model package, implement builder and store support for writing only manifest and config, and update CLI logic and documentation accordingly.

New Features:
- Add --from flag to docker model package for creating variants from existing models
- Support lightweight repackaging path that writes only manifest and config for config-only changes

Enhancements:
- Implement builder.FromModel, Builder.Model, and Builder.HasOnlyConfigChanges to enable repackaging workflows
- Introduce WriteLightweightModel in distribution client and WriteLightweight in local store to avoid copying unchanged layer blobs
- Update CLI to detect config-only modifications and route to optimized repackaging path

Documentation:
- Update CLI reference and documentation to describe the --from flag and repackaging workflow

Tests:
- Add comprehensive tests for WriteLightweight store behavior, builder FromModel functionality, and CLI repackaging scenarios including error handling

### CODE REVIEW

File: pkg/distribution/builder/builder_test.go [hunk 1]
```diff
@@ -142,6 +142,154 @@ func TestWithMultimodalProjectorChaining(t *testing.T) {
...
+		t.Fatalf("Failed to build repackaged model: %v", err)
+	}
+
+	// Step 5: Verify the repackaged model has the new context size
+	repackagedConfig, err := repackagedTarget.artifact.Config()
+	if err != nil {
+		t.Fatalf("Failed to get repackaged config: %v", err)
+	}
+
+	if repackagedConfig.ContextSize == nil || *repackagedConfig.ContextSize != 4096 {
```
Comment (juangcarmona) [inline pkg/distribution/builder/builder_test.go:200]: Understood!

**Review by juangcarmona — APPROVED** [review]
Great job! It will work for many of us. Thanks!

**Comment by aleksmelnikov** [comment]
It will be good if the 'docker model ls' can output context_size directly to avoid having to carry out an inspection for this parameter by 'docker model inspect'.

**Comment by ilopezluna** [comment]
> It will be good if the 'docker model ls' can output context_size directly to avoid having to carry out an inspection for this parameter by 'docker model inspect'.

I think that's a great idea, I'll open an issue, in case anyone of you would like to contribute feel free to open a PR!

**Comment by ilopezluna** [comment]
@aleksmelnikov this is the issue: https://github.com/docker/model-runner/issues/246

**Comment by ilopezluna** [comment]
> LGTM, worth reading through the bot comments to see if they are worth picking up.

@ericcurtin the comments related to leaving the store in an inconsistent state, while true, are not related to this PR, as the `store.Write` method is already not atomic and it does not has a rollback mechanism.
I open [an issue](https://github.com/docker/model-runner/issues/267) to address it in a separated PR
