### PR TITLE
Fix/store consistency

### LINKED ISSUE #267: Failures between writing config, manifest, or tags may leave the store inconsistent
Related to [this comment](https://github.com/docker/model-runner/pull/243#discussion_r2444783956).

Currently, the methods that update the Store (e.g., writing the config, manifest, and tags) are not atomic.
If an error occurs in between these steps, for example, after writing the config but before the manifest or tags are persisted, the store may be left in an inconsistent or partially written state.

This can result in:

- Dangling references or incomplete entries in the store.
- Subsequent operations (reads, pushes, or deletions) failing unexpectedly.
- Difficulty in recovering or cleaning up after a failed write.

### Proposed solution

- Make the update operation atomic, either all store updates succeed, or none are persisted.
- Alternatively, implement a rollback mechanism to clean up any partially written data if an intermediate step fails.
- Add tests simulating mid-operation failures to verify that the store remains consistent after recovery.

### PR DESCRIPTION
**Pull request by jwjohns**
- make the store resilient to partial failures when writing models: the config, layers, manifest, and index now land only on success.
  - the new helper writes files through a temp-and-rename flow so updates are atomic, and Write/WriteLightweight capture cleanup actions if something fails mid-flight.
  - add `TestWriteRollsBackOnTagFailure` to prove that a broken tagging step leaves no blobs, manifests, or index entries behind.

  ### Testing

  - `GOCACHE=/tmp/go-cache GOWORK=off go test ./... `(full suite)
  - `GOCACHE=/tmp/go-cache GOWORK=off go test ./pkg/distribution/internal/store -run TestWriteRollsBackOnTagFailure -v` (explicit regression to show rollback works)

  Closes #267.

### CODE REVIEW

**Comment by ericcurtin** [comment]
@ilopezluna WDYT? PTAL

**Comment by jwjohns** [comment]
Let me know what you guys think. This one was a little more in depth and I created it as draft to enable proper discussion prior to any merges.

File: pkg/distribution/internal/store/blobs.go [hunk 1]
```diff
@@ -78,29 +79,33 @@ type blob interface {
...
 	hasBlob, err := s.hasBlob(hash)
 	if err != nil {
-		return fmt.Errorf("check blob existence: %w", err)
+		return false, v1.Hash{}, fmt.Errorf("check blob existence: %w", err)
 	}
 	if hasBlob {
-		// todo: write something to the progress channel (we probably need to redo progress reporting a little bit)
-		return nil
+		// TODO: write something to the progress channel (we probably need to redo progress reporting a little bit)
+		return false, hash, nil
```
Comment (ilopezluna) [inline pkg/distribution/internal/store/blobs.go:94]: I was wondering, why not just use the `error` to determine whether the blob was created? If `error` is `nil`, it would mean the blob was created. However, this assumption is incorrect when the blob already exists. In that case, there’s no error, but no new blob is added. Therefore, there’s no need to keep track of the blob for cleanup in case of a rollback.

Did I understand that correctly?

File: pkg/distribution/internal/store/blobs.go [hunk 2]
```diff
@@ -169,19 +174,29 @@ func incompletePath(path string) string {
...
-func (s *LocalStore) writeConfigFile(mdl v1.Image) error {
+// writeConfigFile writes the model config JSON file to the blob store and reports whether the file was newly created.
+func (s *LocalStore) writeConfigFile(mdl v1.Image) (bool, error) {
 	hash, err := mdl.ConfigName()
 	if err != nil {
-		return fmt.Errorf("get digest: %w", err)
+		return false, fmt.Errorf("get digest: %w", err)
 	}
-	rcf, err := mdl.RawConfigFile()
+	path, err := s.blobPath(hash)
```
Comment (ilopezluna) [inline pkg/distribution/internal/store/blobs.go]: Oh we missed that case thanks!
You could also use `s.hasBlob(hash)` here

File: pkg/distribution/internal/store/manifests.go [hunk 3]
```diff
@@ -43,7 +44,14 @@ func (s *LocalStore) WriteManifest(hash v1.Hash, raw []byte) error {
 		return fmt.Errorf("reading models: %w", err)
 	}
 
-	return s.writeIndex(idx.Add(newEntryForManifest(hash, manifest)))
+	if err := s.writeIndex(idx.Add(newEntryForManifest(hash, manifest))); err != nil {
+		// Best effort rollback to avoid leaving an orphaned manifest on disk.
+		if removeErr := s.removeManifest(hash); removeErr != nil && !errors.Is(removeErr, os.ErrNotExist) {
+			return fmt.Errorf("writing models index: %w (also failed to remove manifest: %v)", err, removeErr)
+		}
```
Comment (ilopezluna) [inline pkg/distribution/internal/store/manifests.go:54]:
```suggestion
if removeErr := s.removeManifest(hash); removeErr != nil && !errors.Is(removeErr, os.ErrNotExist) {
		return errors.Join(
			fmt.Errorf("write models index: %w", err),
			fmt.Errorf("rollback remove manifest %s: %w", hash, removeErr),
		)
	}```

File: pkg/distribution/internal/store/store_test.go [hunk 4]
```diff
@@ -382,6 +382,88 @@ func TestStoreAPI(t *testing.T) {
 	})
 }
 
+func TestWriteRollsBackOnTagFailure(t *testing.T) {
```
Comment (ilopezluna) [inline pkg/distribution/internal/store/store_test.go:387]: Thanks for adding a test of tag failure, could you also add one for config failure and layer failure? 🙏 
Ideally we should also add test of failure with an already existing blob but we can do it in a follow up PR

**Review by ilopezluna — APPROVED** [review]
@jwjohns thank you so much for looking into this! I don’t see anything blocking in this PR, so I’ve already approved it. I added some comments, but they’re just nice-to-have improvements we can merge this as it is and address them in a follow-up PR.
Of course, if you’d prefer to address the comments in this same PR, that’s perfect too!

**Comment by jwjohns** [comment]
@ilopezluna i will get them handled shortly.

**Comment by jwjohns** [comment]
@ilopezluna changes are in. I will take out of draft status and set for review for you. I went ahead and did everything except the blob check. I will get that PR in as well soon.

File: pkg/distribution/internal/store/store.go [hunk 5]
```diff
@@ -200,10 +201,41 @@ func (s *LocalStore) Version() string {
...
+
+	type cleanupFunc func() error
+	var cleanups []cleanupFunc
+	success := false
+	defer func() {
+		if success {
+			return
+		}
+		for i := len(cleanups) - 1; i >= 0; i-- {
+			if err := cleanups[i](); err != nil && !errors.Is(err, os.ErrNotExist) {
```
[the remark this answers is not in the document]
Comment (jwjohns) [reply pkg/distribution/internal/store/store.go]: will handle these as well.

**Comment by jwjohns** [comment]
@ilopezluna I got your requested changes in and also the ones sorcery-ai recommended. I can do the blob in another PR tomorrow
